#!/usr/bin/env bash
# configures an ubuntu server with the below req
# localhost 127.0.0.2
# facebook.com 8.8.8.8

cp /etc/hosts ~/hosts.new
echo "8.8.8.8		facebook.com" > ~/hosts.new
echo "127.0.0.2		localhost" >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts
